### ISSUE TITLE
Arduino Micro compatibility?

### ISSUE THREAD

**Issue by Roet-Ivar** [sanzoghenzo/nes_adapter#1]
I have a Arduino Micro (atmega 32u4) I wonder if this code could easily be compatible with this?
I've tried uploading the hex to the device but I don't get any new HID device in windows.
Thanks!

**Comment by sanzoghenzo** [comment]
Hi!

I'm not sure, but there's the [Arduino-LUFA project](https://github.com/Palatis/Arduino-Lufa) that could help in this process.

To change the target platfrom of the compilation, you just need to set the first variables in the makefile.

Good luck!

**Comment by Roet-Ivar** [comment]
Thank you, I wish you a great day!
